apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: banking # ns
data:
  # DB_HOST: "postgres-db" # DB_name that will be created to the service later
  DB_HOST: "postgres-db-0.postgres-svc.banking.svc.cluster.local"
  DB_USER: "bankuser"
  
  DB_NAME: "banking_db"
  DB_DATABASE: "banking_db"
  POSTGRES_DB: "banking_db"

  DB_PORT: "5432"
  LOG_LEVEL: "debug"
  MAX_TRANSACTION_LIMIT: "10000"
