apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: banking
type: Opaque
stringData:
  # دي الباسوورد اللي الـ API مستنيها بالظبط
  postgres-password: "password123" 
  # باسوورد إضافية للـ Replication (ممكن تسيبها زي ما هي)
  replication-password: "Repl!Secure99"